// Generated by scripts/optimize-illustrations.mjs (npm run optimize:illustrations). Do not edit by hand.
// width/height are those of the "full" image; the card image has the same aspect ratio.
export const ILLUSTRATION_IMAGES = {
  aurora: { card: "/illustrations/aurora-card.webp", full: "/illustrations/aurora.webp", width: 2000, height: 1476 },
  tigre: { card: "/illustrations/tigre-card.webp", full: "/illustrations/tigre.webp", width: 1440, height: 1747 },
  poki: { card: "/illustrations/poki-card.webp", full: "/illustrations/poki.webp", width: 932, height: 1080 },
  whitebird: { card: "/illustrations/whitebird-card.webp", full: "/illustrations/whitebird.webp", width: 864, height: 1080 },
  sacred: { card: "/illustrations/sacred-card.webp", full: "/illustrations/sacred.webp", width: 1724, height: 2000 },
} as const;
